# Generated by Django 4.1.1 on 2022-10-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
