# Generated by Django 4.1.1 on 2022-10-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passwd', models.CharField(blank=True, max_length=20, null=True)),
                ('nickname', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
