# Generated by Django 4.1.1 on 2022-10-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_photo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Category",
        ),
    ]
