# Generated by Django 4.1.1 on 2022-10-28 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0008_alter_category_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
