# Generated by Django 4.1.1 on 2022-11-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0010_category1_category2_delete_category"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="category1",
            table="category1",
        ),
        migrations.AlterModelTable(
            name="category2",
            table="category2",
        ),
    ]
